### ISSUE TITLE
NAT Masquerade breakage

### ISSUE THREAD

**Issue by tomislacker** [mrlesmithjr/ansible-firewalld#2]
Unless I'm out of my mind, I would expect the following:

```
 firewalld_rules:                                                                                                                                                                                                                                                               
   ########################                                                                                                                                                                                                                                                     
   # Routing & Forwarding #                                                                                                                                                                                                                                                     
   ########################                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                
   # Masquerading out 'dmz' zone interfaces                                                                                                                                                                                                                                     
   - masquerade: yes                                                                                                                                                                                                                                                            
     permanent: true                                                                                                                                                                                                                                                            
     zone: dmz                                                                                                                                                                                                                                                                  
     state: enabled
```

Not to cause this error:

```
TASK [mrlesmithjr.firewalld : rules | Managing Firewall Rules] ************************************************************************
task path: /home/meh/Projects/mydomain/roles/mrlesmithjr.firewalld/tasks/rules.yml:2
failed: [mybox] (item={'masquerade': True, 'permanent': True, 'zone': 'dmz', 'state': 'enabled'}) => {
    "failed": true,
    "item": {
        "masquerade": true,
        "permanent": true,
        "state": "enabled",
        "zone": "dmz"
    }
}

MSG:

ERROR: Exception caught: set_masquerade_enabled() takes exactly 1 argument (3 given)
```
